version: "3.9"
services:
  mysql:
    image: "mysql:5.7"
    environment:
      - MYSQL_USER=valentin
      - MYSQL_PASSWORD=malo
      - MYSQL_DATABASE=mysql
      - MYSQL_ROOT_PASSWORD=root
  app:
    image: "ma_super_app"
    links:
      - mysql:db
    ports:
      - "3000:3000"
    depends_on:
      - mysql:db