apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
spec:
  containers:
  - name: mysql-container
    image: mysql:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "root"
    - name: MYSQL_USER
      value: "test"
    - name: MYSQL_PASSWORD
      value: "password"
    ports:
    - containerPort: 3306