apiVersion: v1
kind: Pod
metadata:
  name: phpmyadmin-pod
spec:
  containers:
  - name: phpmyadmin-container
    image: phpmyadmin/phpmyadmin
    env:
    - name: PMA_HOST
      value: mysql-service
    - name: PMA_PORT
      value: "3306"
    ports:
    - containerPort: 80